### ISSUE TITLE
Provide sensible default colours for targets

### ISSUE THREAD

**Issue by rgommezz** [callstack-io/react-native-material-palette#2]
We will need to decide the default colours based on the options, for example `darkMuted` should give a dark grey colour, `darkVibrant` should give pitch black, `lightMuted`, a light colour, etc.

**Comment by rgommezz** [comment]
![image](https://user-images.githubusercontent.com/4982414/28679464-950dd146-72f3-11e7-9da6-b8a05c8897f6.png)

![image](https://user-images.githubusercontent.com/4982414/28679663-3a38a916-72f4-11e7-88fc-bafd2803554d.png)

![image](https://user-images.githubusercontent.com/4982414/28679787-8fa4333e-72f4-11e7-94e3-6bce0501d1be.png)

![image](https://user-images.githubusercontent.com/4982414/28680042-68fae088-72f5-11e7-86c3-a2a41c255777.png)

**Comment by rgommezz** [comment]
After extrapolating with my eyes a bit, we could use those as defaults:

Light Vibrant: 
![image](https://user-images.githubusercontent.com/4982414/28680323-4beeb536-72f6-11e7-994c-be711440b296.png)

Vibrant: 
![image](https://user-images.githubusercontent.com/4982414/28680276-1f377b86-72f6-11e7-8bcf-afb7d0b06ef4.png)

Dark Vibrant:
![image](https://user-images.githubusercontent.com/4982414/28680299-342c8770-72f6-11e7-9dc4-4517f4351806.png)

Light Muted:
![image](https://user-images.githubusercontent.com/4982414/28680198-f22935bc-72f5-11e7-9c7b-0b1c72ae09ba.png)

Muted:
![image](https://user-images.githubusercontent.com/4982414/28680337-56b1a4b0-72f6-11e7-82df-43f82e6bf6f7.png)

Dark Muted:
![image](https://user-images.githubusercontent.com/4982414/28680353-6322e22c-72f6-11e7-819e-e655c78130e7.png)


@satya164, @zamotany what do you guys think?

**Comment by satya164** [comment]
I'd make the lighter one as light vibrant, and the darker one as light muted
