### ISSUE TITLE
Split flow and test into spearate tasks and add color support

### ISSUE THREAD

**Issue by zamotany** [callstack-io/react-native-material-palette#24]
Right now we have `.circle` folder which is used by version 2 and `circle.yml` for version 1. We should remove one of them. Also, don't we want to check types with flow on Circle??

**Comment by rgommezz** [comment]
Oh, I didn't know you also added it in your branch! I had set it up in master for version 2. I'll make a small PR to fix it

**Comment by zamotany** [comment]
I've merged #25 but we should try to split `yarn run flow && yarn run jest -- -i --coverage` into 2 tasks so that they doesn't appear in ingle foldable container in Circle. Also colors support would be nice.
